name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: poetry install --with dev,ci

      - name: Unit tests and coverage
        run: | 
          poetry run coverage run -m nose2
          poetry run coverage xml

      - name: Code Coverage Report
        run: | 
          poetry run coverage report --omit "/usr/*"
          cov=$(poetry run coverage report --omit "/usr/*" | grep TOTAL | awk '{print $4}')
          echo $cov
          echo "COVERAGE=${cov:0:-1}" >> $GITHUB_ENV

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.SEISSOL_MATRICES_GIST }}
          gistID: b9c4e4cac4b1c91e4645e5a319e18c9a
          filename: seissol-matrices.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          valColorRange: ${{ env.COVERAGE }}
          maxColorRange: 100
          minColorRange: 0k
          forceUpdate: true

      - name: Coding style
        run: |
          poetry run black --check src
          poetry run black --check tests