name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: pip install nose2 coverage numpy scipy quadpy orthopy ndim

      - name: Unit tests and coverage
        run: coverage run -m nose2
