name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Prepare environment
        run: pip install nose2 coverage numpy scipy quadpy orthopy ndim

      - name: Unit tests and coverage
        run: | 
          coverage run -m nose2
          coverage xml

      - name: Code Coverage Report
        run: | 
          pip install coverage-badge
          coverage report --omit "/usr/*"
          cov=$(coverage report --omit "usr/*" | grep TOTAL | awk '{print $4}')
          echo "COVERAGE=${cov:0:-1}" >> $GITHUB_ENV

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.SEISSOL_MATRICES_GIST }}
          gistID: b9c4e4cac4b1c91e4645e5a319e18c9a
          filename: seissol-matrices.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          valColorRange: ${{ env.COVERAGE }}
          maxColorRange: 100
          minColorRange: 0k
          forceUpdate: true

  coding-style:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Prepare environment
        run: pip install black

      - name: Coding style
        run: |
          black --check seissol_matrices
          black --check tests
